import React, { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { apiRequest } from "../api/client";

export default function ResolutionComplete() {
  const { roomId } = useParams();
  const navigate = useNavigate();
  const { token } = useAuth();
  const [room, setRoom] = useState(null);
  const [summaries, setSummaries] = useState(null);
  const [transcript, setTranscript] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadResolution = async () => {
      try {
        // Get room details
        const roomData = await apiRequest(`/rooms/${roomId}`, "GET", null, token);
        setRoom(roomData);
        
        // Get summaries
        const summariesData = await apiRequest(`/rooms/${roomId}/main-room/summaries`, "GET", null, token);
        setSummaries(summariesData);

        // Get full conversation transcript
        const transcriptData = await apiRequest(`/rooms/${roomId}/main-room/messages`, "GET", null, token);
        setTranscript(transcriptData.messages || []);
      } catch (error) {
        console.error("Load error:", error);
      }
      setLoading(false);
    };
    
    loadResolution();
  }, [roomId, token]);

  if (loading) {
    return <div style={{ textAlign: "center", padding: "60px" }}>Loading...</div>;
  }

  if (!room || !summaries) {
    return <div style={{ textAlign: "center", padding: "60px" }}>Resolution not found</div>;
  }

  const checkInDate = room.check_in_date ? new Date(room.check_in_date).toLocaleDateString() : "1 week";

  const downloadTranscript = () => {
    const transcriptText = `MEEDI8 MEDIATION TRANSCRIPT
Room: ${room.title}
Date: ${new Date(room.created_at).toLocaleDateString()}

=== ORIGINAL PERSPECTIVES ===

${summaries.user1_name}:
${summaries.user1_summary}

${summaries.user2_name}:
${summaries.user2_summary}

=== CONVERSATION ===

${transcript.map(msg => {
  if (msg.role === 'assistant') {
    return `AI Mediator: ${msg.content}`;
  } else if (msg.role === 'resolution') {
    return `\n=== AGREEMENT REACHED ===\n${msg.content}`;
  } else {
    const userName = msg.userId === summaries.user1_id ? summaries.user1_name : summaries.user2_name;
    return `${userName}: ${msg.content}`;
  }
}).join('\n\n')}

=== FINAL AGREEMENT ===

${room.resolution_text}

---
Generated by Meedi8 - AI-Powered Mediation
${new Date().toLocaleString()}
`;

    const blob = new Blob([transcriptText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `clean-air-transcript-${roomId}-${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div style={{ maxWidth: "800px", margin: "0 auto", padding: "40px 20px" }}>
      {/* Celebration Header */}
      <div style={{ textAlign: "center", marginBottom: "40px" }}>
        <div style={{ fontSize: "80px", marginBottom: "16px" }}>🎉</div>
        <h1 style={{ fontSize: "36px", marginBottom: "12px", color: "#10b981" }}>
          You Did It!
        </h1>
        <p style={{ fontSize: "18px", color: "#6b7280", maxWidth: "600px", margin: "0 auto" }}>
          You both listened to each other, understood different perspectives, and found a solution together. 
          This is what great communication looks like.
        </p>
      </div>

      {/* Agreement Box */}
      <div style={{ 
        background: "#dcfce7", 
        border: "2px solid #10b981", 
        borderRadius: "16px", 
        padding: "32px",
        marginBottom: "32px"
      }}>
        <h2 style={{ fontSize: "24px", marginBottom: "16px", color: "#065f46", display: "flex", alignItems: "center", gap: "8px" }}>
          <span>✅</span> Your Agreement
        </h2>
        <div style={{ 
          fontSize: "16px", 
          lineHeight: "1.8", 
          color: "#065f46",
          whiteSpace: "pre-wrap",
          marginBottom: "24px"
        }}>
          {room.resolution_text}
        </div>
        
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px" }}>
          <button
            onClick={downloadTranscript}
            style={{
              background: "#a7f3d0",
              padding: "16px",
              borderRadius: "8px",
              border: "none",
              display: "flex",
              alignItems: "center",
              gap: "12px",
              cursor: "pointer",
              transition: "background 0.2s",
              textAlign: "left"
            }}
            onMouseEnter={(e) => e.currentTarget.style.background = "#86efac"}
            onMouseLeave={(e) => e.currentTarget.style.background = "#a7f3d0"}
          >
            <span style={{ fontSize: "24px" }}>💾</span>
            <div>
              <div style={{ fontWeight: "600", color: "#065f46", marginBottom: "4px" }}>
                Download Transcript
              </div>
              <div style={{ fontSize: "14px", color: "#047857" }}>
                Save your full conversation
              </div>
            </div>
          </button>

          <a
            href={`https://calendar.google.com/calendar/render?action=TEMPLATE&text=Clean%20Air%20Check-in&dates=${room.check_in_date?.replace(/-/g, '')}T120000/${room.check_in_date?.replace(/-/g, '')}T130000&details=Review%20how%20your%20mediation%20agreement%20is%20working.%20Return%20to%20Clean%20Air%20if%20you%20need%20support.&location=Clean%20Air%20App`}
            target="_blank"
            rel="noopener noreferrer"
            style={{ textDecoration: "none", display: "block" }}
          >
            <div style={{
              background: "#a7f3d0",
              padding: "16px",
              borderRadius: "8px",
              display: "flex",
              alignItems: "center",
              gap: "12px",
              cursor: "pointer",
              transition: "background 0.2s",
              height: "100%"
            }}
            onMouseEnter={(e) => e.currentTarget.style.background = "#86efac"}
            onMouseLeave={(e) => e.currentTarget.style.background = "#a7f3d0"}
            >
              <span style={{ fontSize: "24px" }}>📅</span>
              <div>
                <div style={{ fontWeight: "600", color: "#065f46", marginBottom: "4px" }}>
                  Add to Calendar ›
                </div>
                <div style={{ fontSize: "14px", color: "#047857" }}>
                  Review on <strong>{checkInDate}</strong>
                </div>
              </div>
            </div>
          </a>
        </div>
      </div>

      {/* Original Perspectives */}
      <div style={{ marginBottom: "32px" }}>
        <h3 style={{ fontSize: "18px", marginBottom: "16px", color: "#374151" }}>
          Where You Started
        </h3>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px" }}>
          <div style={{ background: "#f9fafb", padding: "20px", borderRadius: "12px", border: "1px solid #e5e7eb" }}>
            <div style={{ fontWeight: "600", marginBottom: "8px", color: "#6b7280", fontSize: "14px" }}>
              {summaries.user1_name}:
            </div>
            <div style={{ fontSize: "14px", lineHeight: "1.6", color: "#374151" }}>
              {summaries.user1_summary.substring(0, 200)}...
            </div>
          </div>
          <div style={{ background: "#f9fafb", padding: "20px", borderRadius: "12px", border: "1px solid #e5e7eb" }}>
            <div style={{ fontWeight: "600", marginBottom: "8px", color: "#6b7280", fontSize: "14px" }}>
              {summaries.user2_name}:
            </div>
            <div style={{ fontSize: "14px", lineHeight: "1.6", color: "#374151" }}>
              {summaries.user2_summary.substring(0, 200)}...
            </div>
          </div>
        </div>
      </div>

      {/* What Made This Work */}
      <div style={{ 
        background: "#eff6ff", 
        padding: "24px", 
        borderRadius: "12px",
        marginBottom: "32px"
      }}>
        <h3 style={{ fontSize: "18px", marginBottom: "12px", color: "#1e40af" }}>
          💪 What Made This Work
        </h3>
        <ul style={{ margin: 0, paddingLeft: "20px", color: "#1e40af" }}>
          <li style={{ marginBottom: "8px" }}>You both took time to prepare your thoughts</li>
          <li style={{ marginBottom: "8px" }}>You listened to understand, not just to respond</li>
          <li style={{ marginBottom: "8px" }}>You focused on needs, not just positions</li>
          <li>You created a specific, actionable plan together</li>
        </ul>
      </div>

      {/* Actions */}
      <div style={{ display: "flex", gap: "12px", justifyContent: "center" }}>
        <button
          onClick={() => navigate("/rooms")}
          style={{
            padding: "16px 32px",
            background: "#3b82f6",
            color: "white",
            border: "none",
            borderRadius: "8px",
            fontSize: "16px",
            fontWeight: "600",
            cursor: "pointer"
          }}
        >
          Back to My Rooms
        </button>
        <button
          onClick={() => navigate("/create")}
          style={{
            padding: "16px 32px",
            background: "#f3f4f6",
            color: "#374151",
            border: "1px solid #e5e7eb",
            borderRadius: "8px",
            fontSize: "16px",
            fontWeight: "600",
            cursor: "pointer"
          }}
        >
          Start New Mediation
        </button>
      </div>
    </div>
  );
}
