"""Add visibility_tier and hint to achievements

Revision ID: 175606bccb37
Revises: def16f58442b
Create Date: 2025-11-22 15:46:24.474287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '175606bccb37'
down_revision: Union[str, Sequence[str], None] = 'def16f58442b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('visibility_tier', sa.String(length=20), nullable=False, server_default='visible'))
    op.add_column('achievements', sa.Column('hint', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'hint')
    op.drop_column('achievements', 'visibility_tier')
    # ### end Alembic commands ###
