"""add_telegram_fields_to_users

Revision ID: 21ab3ff7a9d9
Revises: add_usage_counters
Create Date: 2025-11-14 11:56:42.945691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21ab3ff7a9d9'
down_revision: Union[str, Sequence[str], None] = 'add_usage_counters'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add Telegram fields to users table
    op.add_column('users', sa.Column('telegram_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('telegram_username', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('telegram_phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('telegram_session_string', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('telegram_connected_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop Telegram fields from users table
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_column('users', 'telegram_connected_at')
    op.drop_column('users', 'telegram_session_string')
    op.drop_column('users', 'telegram_phone')
    op.drop_column('users', 'telegram_username')
    op.drop_column('users', 'telegram_id')
    # ### end Alembic commands ###
