"""add professional report fields to room

Revision ID: 30afec47f5c9
Revises: 6e6326293b4b
Create Date: 2025-11-10 21:46:51.546600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30afec47f5c9'
down_revision: Union[str, Sequence[str], None] = '6e6326293b4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('free', 'plus', 'pro', name='subscriptiontier'), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'expired', 'trial', name='subscriptionstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('voice_conversations_used', sa.Integer(), nullable=False),
    sa.Column('voice_conversations_limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_table('user_health_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_full_screening', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('needs_update', sa.Boolean(), nullable=True),
    sa.Column('has_mental_health_condition', sa.Boolean(), nullable=True),
    sa.Column('mental_health_conditions', sa.JSON(), nullable=True),
    sa.Column('condition_details', sa.Text(), nullable=True),
    sa.Column('currently_in_treatment', sa.Boolean(), nullable=True),
    sa.Column('treatment_types', sa.JSON(), nullable=True),
    sa.Column('treatment_frequency', sa.String(length=50), nullable=True),
    sa.Column('has_crisis_plan', sa.Boolean(), nullable=True),
    sa.Column('emergency_contact_available', sa.Boolean(), nullable=True),
    sa.Column('verbal_aggression_history', sa.String(length=20), nullable=True),
    sa.Column('physical_aggression_history', sa.String(length=20), nullable=True),
    sa.Column('last_aggression_incident', sa.Date(), nullable=True),
    sa.Column('aggression_context', sa.Text(), nullable=True),
    sa.Column('alcohol_use', sa.String(length=20), nullable=True),
    sa.Column('drug_use', sa.String(length=20), nullable=True),
    sa.Column('substance_details', sa.JSON(), nullable=True),
    sa.Column('substances_affect_behavior', sa.Boolean(), nullable=True),
    sa.Column('feels_generally_safe', sa.Boolean(), nullable=True),
    sa.Column('has_safety_plan', sa.Boolean(), nullable=True),
    sa.Column('safety_concerns', sa.Text(), nullable=True),
    sa.Column('baseline_risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('prefers_professional_mediator', sa.Boolean(), nullable=True),
    sa.Column('comfortable_with_ai_mediation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_health_profiles_id'), 'user_health_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_health_profiles_user_id'), 'user_health_profiles', ['user_id'], unique=True)
    op.create_table('session_screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('health_profile_id', sa.Integer(), nullable=True),
    sa.Column('is_returning_user', sa.Boolean(), nullable=True),
    sa.Column('profile_still_accurate', sa.Boolean(), nullable=True),
    sa.Column('reported_changes', sa.Boolean(), nullable=True),
    sa.Column('changes_description', sa.Text(), nullable=True),
    sa.Column('feeling_state', sa.String(length=20), nullable=True),
    sa.Column('feels_safe_today', sa.Boolean(), nullable=True),
    sa.Column('under_substance_influence', sa.Boolean(), nullable=True),
    sa.Column('substance_influence_details', sa.Text(), nullable=True),
    sa.Column('recent_crisis', sa.Boolean(), nullable=True),
    sa.Column('crisis_details', sa.Text(), nullable=True),
    sa.Column('recent_aggression', sa.Boolean(), nullable=True),
    sa.Column('aggression_details', sa.Text(), nullable=True),
    sa.Column('concerns_about_other_person', sa.Boolean(), nullable=True),
    sa.Column('other_person_concerns', sa.Text(), nullable=True),
    sa.Column('willing_to_proceed', sa.Boolean(), nullable=True),
    sa.Column('session_risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_reasons', sa.JSON(), nullable=True),
    sa.Column('screening_passed', sa.Boolean(), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('resources_provided', sa.JSON(), nullable=True),
    sa.Column('screened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['health_profile_id'], ['user_health_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_screenings_id'), 'session_screenings', ['id'], unique=False)
    op.create_index(op.f('ix_session_screenings_room_id'), 'session_screenings', ['room_id'], unique=False)
    op.create_index(op.f('ix_session_screenings_user_id'), 'session_screenings', ['user_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('addressed_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['addressed_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_id'), 'turns', ['id'], unique=False)
    op.create_table('api_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('turn_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('audio_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_costs_created_at'), 'api_costs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_costs_id'), 'api_costs', ['id'], unique=False)
    op.create_index(op.f('ix_api_costs_service_type'), 'api_costs', ['service_type'], unique=False)
    op.alter_column('room_participants', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('room_participants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_room_participants_room_id'), table_name='room_participants')
    op.drop_index(op.f('ix_room_participants_user_id'), table_name='room_participants')
    op.drop_column('room_participants', 'role')
    op.drop_column('room_participants', 'id')
    op.drop_column('room_participants', 'created_at')
    op.add_column('rooms', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('rooms', sa.Column('phase', sa.String(), nullable=False))
    op.add_column('rooms', sa.Column('invite_token', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('user1_summary', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('user2_summary', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('resolution_text', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('check_in_date', sa.Date(), nullable=True))
    op.add_column('rooms', sa.Column('professional_report', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('report_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('break_requested_by_id', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('break_requested_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('last_speaker_id', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('consecutive_questions_to_same', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('breathing_break_count', sa.Integer(), nullable=True))
    op.add_column('rooms', sa.Column('last_breathing_break_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('user1_last_seen_main_room', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('user2_last_seen_main_room', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('rooms', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('rooms', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('rooms', 'key_insights',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('rooms', 'suggested_actions',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('rooms', 'converted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_invite_token'), 'rooms', ['invite_token'], unique=True)
    op.create_foreign_key(None, 'rooms', 'users', ['break_requested_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('has_completed_screening', sa.Boolean(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.alter_column('users', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)
    op.drop_column('users', 'has_completed_screening')
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_index(op.f('ix_rooms_invite_token'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.alter_column('rooms', 'converted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('rooms', 'suggested_actions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('rooms', 'key_insights',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('rooms', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('rooms', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('rooms', 'user2_last_seen_main_room')
    op.drop_column('rooms', 'user1_last_seen_main_room')
    op.drop_column('rooms', 'last_breathing_break_at')
    op.drop_column('rooms', 'breathing_break_count')
    op.drop_column('rooms', 'consecutive_questions_to_same')
    op.drop_column('rooms', 'last_speaker_id')
    op.drop_column('rooms', 'break_requested_at')
    op.drop_column('rooms', 'break_requested_by_id')
    op.drop_column('rooms', 'report_generated_at')
    op.drop_column('rooms', 'professional_report')
    op.drop_column('rooms', 'check_in_date')
    op.drop_column('rooms', 'resolved_at')
    op.drop_column('rooms', 'resolution_text')
    op.drop_column('rooms', 'user2_summary')
    op.drop_column('rooms', 'user1_summary')
    op.drop_column('rooms', 'invite_token')
    op.drop_column('rooms', 'phase')
    op.drop_column('rooms', 'category')
    op.add_column('room_participants', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('room_participants', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('room_participants', sa.Column('role', sa.VARCHAR(length=50), nullable=True))
    op.create_index(op.f('ix_room_participants_user_id'), 'room_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_room_participants_room_id'), 'room_participants', ['room_id'], unique=False)
    op.alter_column('room_participants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('room_participants', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_api_costs_service_type'), table_name='api_costs')
    op.drop_index(op.f('ix_api_costs_id'), table_name='api_costs')
    op.drop_index(op.f('ix_api_costs_created_at'), table_name='api_costs')
    op.drop_table('api_costs')
    op.drop_index(op.f('ix_turns_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_session_screenings_user_id'), table_name='session_screenings')
    op.drop_index(op.f('ix_session_screenings_room_id'), table_name='session_screenings')
    op.drop_index(op.f('ix_session_screenings_id'), table_name='session_screenings')
    op.drop_table('session_screenings')
    op.drop_index(op.f('ix_user_health_profiles_user_id'), table_name='user_health_profiles')
    op.drop_index(op.f('ix_user_health_profiles_id'), table_name='user_health_profiles')
    op.drop_table('user_health_profiles')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
