"""add report payment tracking

Revision ID: 3ed667894635
Revises: 175606bccb37
Create Date: 2025-11-22 22:38:35.726498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ed667894635'
down_revision: Union[str, Sequence[str], None] = '175606bccb37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('report_payment_id', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('report_paid_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'report_paid_at')
    op.drop_column('rooms', 'report_payment_id')
    # ### end Alembic commands ###
