"""add_clinical_screening_models

Revision ID: 6e6326293b4b
Revises: 210d0dd828a6
Create Date: 2025-11-09 20:03:17.761618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e6326293b4b'
down_revision: Union[str, Sequence[str], None] = '210d0dd828a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_health_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_full_screening', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('needs_update', sa.Boolean(), nullable=True),
    sa.Column('has_mental_health_condition', sa.Boolean(), nullable=True),
    sa.Column('mental_health_conditions', sa.JSON(), nullable=True),
    sa.Column('condition_details', sa.Text(), nullable=True),
    sa.Column('currently_in_treatment', sa.Boolean(), nullable=True),
    sa.Column('treatment_types', sa.JSON(), nullable=True),
    sa.Column('treatment_frequency', sa.String(length=50), nullable=True),
    sa.Column('has_crisis_plan', sa.Boolean(), nullable=True),
    sa.Column('emergency_contact_available', sa.Boolean(), nullable=True),
    sa.Column('verbal_aggression_history', sa.String(length=20), nullable=True),
    sa.Column('physical_aggression_history', sa.String(length=20), nullable=True),
    sa.Column('last_aggression_incident', sa.Date(), nullable=True),
    sa.Column('aggression_context', sa.Text(), nullable=True),
    sa.Column('alcohol_use', sa.String(length=20), nullable=True),
    sa.Column('drug_use', sa.String(length=20), nullable=True),
    sa.Column('substance_details', sa.JSON(), nullable=True),
    sa.Column('substances_affect_behavior', sa.Boolean(), nullable=True),
    sa.Column('feels_generally_safe', sa.Boolean(), nullable=True),
    sa.Column('has_safety_plan', sa.Boolean(), nullable=True),
    sa.Column('safety_concerns', sa.Text(), nullable=True),
    sa.Column('baseline_risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_factors', sa.JSON(), nullable=True),
    sa.Column('prefers_professional_mediator', sa.Boolean(), nullable=True),
    sa.Column('comfortable_with_ai_mediation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_health_profiles_id'), 'user_health_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_health_profiles_user_id'), 'user_health_profiles', ['user_id'], unique=True)
    op.create_table('session_screenings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('health_profile_id', sa.Integer(), nullable=True),
    sa.Column('is_returning_user', sa.Boolean(), nullable=True),
    sa.Column('profile_still_accurate', sa.Boolean(), nullable=True),
    sa.Column('reported_changes', sa.Boolean(), nullable=True),
    sa.Column('changes_description', sa.Text(), nullable=True),
    sa.Column('feeling_state', sa.String(length=20), nullable=True),
    sa.Column('feels_safe_today', sa.Boolean(), nullable=True),
    sa.Column('under_substance_influence', sa.Boolean(), nullable=True),
    sa.Column('substance_influence_details', sa.Text(), nullable=True),
    sa.Column('recent_crisis', sa.Boolean(), nullable=True),
    sa.Column('crisis_details', sa.Text(), nullable=True),
    sa.Column('recent_aggression', sa.Boolean(), nullable=True),
    sa.Column('aggression_details', sa.Text(), nullable=True),
    sa.Column('concerns_about_other_person', sa.Boolean(), nullable=True),
    sa.Column('other_person_concerns', sa.Text(), nullable=True),
    sa.Column('willing_to_proceed', sa.Boolean(), nullable=True),
    sa.Column('session_risk_level', sa.String(length=20), nullable=True),
    sa.Column('risk_reasons', sa.JSON(), nullable=True),
    sa.Column('screening_passed', sa.Boolean(), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=True),
    sa.Column('resources_provided', sa.JSON(), nullable=True),
    sa.Column('screened_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['health_profile_id'], ['user_health_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_screenings_id'), 'session_screenings', ['id'], unique=False)
    op.create_index(op.f('ix_session_screenings_room_id'), 'session_screenings', ['room_id'], unique=False)
    op.create_index(op.f('ix_session_screenings_user_id'), 'session_screenings', ['user_id'], unique=False)
    # Note: api_costs table already exists from earlier migration, not creating it here
    op.alter_column('room_participants', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('room_participants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rooms', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('rooms', 'invite_token',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ix_rooms_invite_token'), table_name='rooms')
    op.create_index(op.f('ix_rooms_invite_token'), 'rooms', ['invite_token'], unique=True)
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    # Note: Foreign key constraints already exist from earlier migrations, skipping drop/recreate
    # op.drop_constraint(None, 'rooms', type_='foreignkey')
    # op.drop_constraint(None, 'rooms', type_='foreignkey')
    # op.drop_constraint(None, 'rooms', type_='foreignkey')
    # op.create_foreign_key(None, 'rooms', 'users', ['break_requested_by_id'], ['id'], ondelete='SET NULL')
    # Note: current_speaker_id column was already removed in an earlier migration
    # op.drop_column('rooms', 'current_speaker_id')
    # Note: These columns already exist from add_subscriptions_and_api_costs migration
    # op.add_column('subscriptions', sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    # op.add_column('subscriptions', sa.Column('end_date', sa.DateTime(timezone=True), nullable=True))
    # op.add_column('subscriptions', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    # op.add_column('subscriptions', sa.Column('stripe_price_id', sa.String(length=255), nullable=True))
    # op.add_column('subscriptions', sa.Column('voice_conversations_used', sa.Integer(), nullable=False))
    # op.add_column('subscriptions', sa.Column('voice_conversations_limit', sa.Integer(), nullable=False))
    op.alter_column('subscriptions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('subscriptions', 'tier',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('free', 'plus', 'pro', name='subscriptiontier'),
               existing_nullable=False,
               existing_server_default=sa.text("'FREE'"))
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('active', 'cancelled', 'expired', 'trial', name='subscriptionstatus'),
               nullable=False,
               existing_server_default=sa.text("'active'"))
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.drop_column('subscriptions', 'current_period_end')
    op.drop_column('subscriptions', 'current_period_start')
    op.alter_column('turns', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('turns', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('turns', 'cost_usd',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=10, scale=6),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('turns', 'model',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_index(op.f('ix_turns_room_id'), table_name='turns')
    op.create_index(op.f('ix_turns_id'), 'turns', ['id'], unique=False)
    op.drop_constraint(None, 'turns', type_='foreignkey')
    op.drop_constraint(None, 'turns', type_='foreignkey')
    op.create_foreign_key(None, 'turns', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'turns', 'users', ['addressed_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'is_admin',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'turns', type_='foreignkey')
    op.drop_constraint(None, 'turns', type_='foreignkey')
    op.create_foreign_key(None, 'turns', 'users', ['addressed_user_id'], ['id'])
    op.create_foreign_key(None, 'turns', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_turns_id'), table_name='turns')
    op.create_index(op.f('ix_turns_room_id'), 'turns', ['room_id'], unique=False)
    op.alter_column('turns', 'model',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('turns', 'cost_usd',
               existing_type=sa.Numeric(precision=10, scale=6),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
    op.alter_column('turns', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('turns', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('subscriptions', sa.Column('current_period_start', sa.DATETIME(), nullable=True))
    op.add_column('subscriptions', sa.Column('current_period_end', sa.DATETIME(), nullable=True))
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.alter_column('subscriptions', 'status',
               existing_type=sa.Enum('active', 'cancelled', 'expired', 'trial', name='subscriptionstatus'),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'"))
    op.alter_column('subscriptions', 'tier',
               existing_type=sa.Enum('free', 'plus', 'pro', name='subscriptiontier'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'FREE'"))
    op.alter_column('subscriptions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # Note: These columns were not added in this migration, skipping removal in downgrade
    # op.drop_column('subscriptions', 'voice_conversations_limit')
    # op.drop_column('subscriptions', 'voice_conversations_used')
    # op.drop_column('subscriptions', 'stripe_price_id')
    # op.drop_column('subscriptions', 'updated_at')
    # op.drop_column('subscriptions', 'end_date')
    # op.drop_column('subscriptions', 'start_date')
    # Note: current_speaker_id was already removed earlier, not re-adding in downgrade
    # op.add_column('rooms', sa.Column('current_speaker_id', sa.INTEGER(), nullable=True))
    # Note: Foreign key constraints not touched in upgrade, skipping in downgrade
    # op.drop_constraint(None, 'rooms', type_='foreignkey')
    # op.create_foreign_key(None, 'rooms', 'users', ['current_speaker_id'], ['id'])
    # op.create_foreign_key(None, 'rooms', 'users', ['last_speaker_id'], ['id'])
    # op.create_foreign_key(None, 'rooms', 'users', ['break_requested_by_id'], ['id'])
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_invite_token'), table_name='rooms')
    op.create_index(op.f('ix_rooms_invite_token'), 'rooms', ['invite_token'], unique=False)
    op.alter_column('rooms', 'invite_token',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('rooms', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('room_participants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('room_participants', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # Note: api_costs table was not created in this migration, so not dropping it here
    op.drop_index(op.f('ix_session_screenings_user_id'), table_name='session_screenings')
    op.drop_index(op.f('ix_session_screenings_room_id'), table_name='session_screenings')
    op.drop_index(op.f('ix_session_screenings_id'), table_name='session_screenings')
    op.drop_table('session_screenings')
    op.drop_index(op.f('ix_user_health_profiles_user_id'), table_name='user_health_profiles')
    op.drop_index(op.f('ix_user_health_profiles_id'), table_name='user_health_profiles')
    op.drop_table('user_health_profiles')
    # ### end Alembic commands ###
