"""add_category_to_rooms

Revision ID: 71b141593884
Revises: add_deep_exploration
Create Date: 2025-11-07 13:44:26.329730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b141593884'
down_revision: Union[str, Sequence[str], None] = 'add_deep_exploration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # This migration just adds the category column to rooms
    # All other tables/columns already exist from previous migrations
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('category', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'category')
    # ### end Alembic commands ###
