"""add_category_to_rooms

Revision ID: 71b141593884
Revises: add_deep_exploration
Create Date: 2025-11-07 13:44:26.329730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b141593884'
down_revision: Union[str, Sequence[str], None] = 'add_deep_exploration'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tier', sa.Enum('free', 'plus', 'pro', name='subscriptiontier'), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'expired', 'trial', name='subscriptionstatus'), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('voice_conversations_used', sa.Integer(), nullable=False),
    sa.Column('voice_conversations_limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.create_table('turns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turns_id'), 'turns', ['id'], unique=False)
    op.create_table('api_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('turn_id', sa.Integer(), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('audio_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_costs_created_at'), 'api_costs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_costs_id'), 'api_costs', ['id'], unique=False)
    op.create_index(op.f('ix_api_costs_service_type'), 'api_costs', ['service_type'], unique=False)
    op.alter_column('room_participants', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('room_participants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_room_participants_room_id'), table_name='room_participants')
    op.drop_index(op.f('ix_room_participants_user_id'), table_name='room_participants')
    op.drop_column('room_participants', 'id')
    op.drop_column('room_participants', 'created_at')
    op.drop_column('room_participants', 'role')
    op.add_column('rooms', sa.Column('category', sa.String(length=50), nullable=True))
    op.add_column('rooms', sa.Column('phase', sa.String(), nullable=False))
    op.add_column('rooms', sa.Column('invite_token', sa.String(length=100), nullable=True))
    op.add_column('rooms', sa.Column('user1_summary', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('user2_summary', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('resolution_text', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('rooms', sa.Column('check_in_date', sa.Date(), nullable=True))
    op.alter_column('rooms', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.alter_column('rooms', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(now())'))
    op.alter_column('rooms', 'consecutive_questions_to_same',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_rooms_id'), 'rooms', ['id'], unique=False)
    op.create_index(op.f('ix_rooms_invite_token'), 'rooms', ['invite_token'], unique=True)
    op.create_foreign_key(None, 'rooms', 'users', ['break_requested_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=320),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_stripe_customer_id'), 'users', ['stripe_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_stripe_customer_id'), table_name='users')
    op.alter_column('users', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=320),
               existing_nullable=False)
    op.drop_column('users', 'stripe_customer_id')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'hashed_password')
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_index(op.f('ix_rooms_invite_token'), table_name='rooms')
    op.drop_index(op.f('ix_rooms_id'), table_name='rooms')
    op.alter_column('rooms', 'consecutive_questions_to_same',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('rooms', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(now())'))
    op.alter_column('rooms', 'title',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.drop_column('rooms', 'check_in_date')
    op.drop_column('rooms', 'resolved_at')
    op.drop_column('rooms', 'resolution_text')
    op.drop_column('rooms', 'user2_summary')
    op.drop_column('rooms', 'user1_summary')
    op.drop_column('rooms', 'invite_token')
    op.drop_column('rooms', 'phase')
    op.drop_column('rooms', 'category')
    op.add_column('room_participants', sa.Column('role', sa.VARCHAR(length=50), nullable=True))
    op.add_column('room_participants', sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(now())'), nullable=False))
    op.add_column('room_participants', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_index(op.f('ix_room_participants_user_id'), 'room_participants', ['user_id'], unique=False)
    op.create_index(op.f('ix_room_participants_room_id'), 'room_participants', ['room_id'], unique=False)
    op.alter_column('room_participants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('room_participants', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_api_costs_service_type'), table_name='api_costs')
    op.drop_index(op.f('ix_api_costs_id'), table_name='api_costs')
    op.drop_index(op.f('ix_api_costs_created_at'), table_name='api_costs')
    op.drop_table('api_costs')
    op.drop_index(op.f('ix_turns_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    # ### end Alembic commands ###
