"""Add announcements table

Revision ID: dc764a968e2d
Revises: zzzz_add_is_guest
Create Date: 2025-11-22 09:34:48.935212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc764a968e2d'
down_revision: Union[str, Sequence[str], None] = 'zzzz_add_is_guest'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if announcements table already exists (from partial migration)
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    existing_tables = inspector.get_table_names()

    if 'announcements' not in existing_tables:
        op.create_table('announcements',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=255), nullable=False),
            sa.Column('message', sa.Text(), nullable=False),
            sa.Column('type', sa.String(length=50), nullable=False),
            sa.Column('is_active', sa.Boolean(), nullable=False),
            sa.Column('is_dismissible', sa.Boolean(), nullable=False),
            sa.Column('target_audience', sa.String(length=50), nullable=False),
            sa.Column('show_on_pages', sa.String(length=500), nullable=False),
            sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
            sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
            sa.Column('created_by', sa.Integer(), nullable=True),
            sa.Column('view_count', sa.Integer(), nullable=False),
            sa.Column('dismiss_count', sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)

    # Check existing columns before adding (for idempotent migrations)
    subscriptions_columns = [col['name'] for col in inspector.get_columns('subscriptions')]
    turns_columns = [col['name'] for col in inspector.get_columns('turns')]

    if 'rooms_created_this_month' not in subscriptions_columns:
        op.add_column('subscriptions', sa.Column('rooms_created_this_month', sa.Integer(), server_default='0', nullable=False))
    if 'month_reset_date' not in subscriptions_columns:
        op.add_column('subscriptions', sa.Column('month_reset_date', sa.DateTime(timezone=True), nullable=True))
    if 'reports_generated_this_month' not in subscriptions_columns:
        op.add_column('subscriptions', sa.Column('reports_generated_this_month', sa.Integer(), server_default='0', nullable=False))
    if 'reports_limit_per_month' not in subscriptions_columns:
        op.add_column('subscriptions', sa.Column('reports_limit_per_month', sa.Integer(), server_default='10', nullable=False))

    # Check existing indexes before creating
    telegram_downloads_indexes = [idx['name'] for idx in inspector.get_indexes('telegram_downloads')] if 'telegram_downloads' in existing_tables else []
    telegram_messages_indexes = [idx['name'] for idx in inspector.get_indexes('telegram_messages')] if 'telegram_messages' in existing_tables else []
    telegram_sessions_indexes = [idx['name'] for idx in inspector.get_indexes('telegram_sessions')] if 'telegram_sessions' in existing_tables else []

    if 'ix_telegram_downloads_id' not in telegram_downloads_indexes and 'telegram_downloads' in existing_tables:
        op.create_index(op.f('ix_telegram_downloads_id'), 'telegram_downloads', ['id'], unique=False)
    if 'ix_telegram_messages_id' not in telegram_messages_indexes and 'telegram_messages' in existing_tables:
        op.create_index(op.f('ix_telegram_messages_id'), 'telegram_messages', ['id'], unique=False)
    if 'ix_telegram_sessions_id' not in telegram_sessions_indexes and 'telegram_sessions' in existing_tables:
        op.create_index(op.f('ix_telegram_sessions_id'), 'telegram_sessions', ['id'], unique=False)

    if 'attachment_url' not in turns_columns:
        op.add_column('turns', sa.Column('attachment_url', sa.String(length=500), nullable=True))
    if 'attachment_filename' not in turns_columns:
        op.add_column('turns', sa.Column('attachment_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'attachment_filename')
    op.drop_column('turns', 'attachment_url')
    op.drop_index(op.f('ix_telegram_sessions_id'), table_name='telegram_sessions')
    op.drop_index(op.f('ix_telegram_messages_id'), table_name='telegram_messages')
    op.drop_index(op.f('ix_telegram_downloads_id'), table_name='telegram_downloads')
    op.drop_column('subscriptions', 'reports_limit_per_month')
    op.drop_column('subscriptions', 'reports_generated_this_month')
    op.drop_column('subscriptions', 'month_reset_date')
    op.drop_column('subscriptions', 'rooms_created_this_month')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_table('announcements')
    # ### end Alembic commands ###
